apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: okd-deployments
  description: Todos los deployments importados desde OKD
spec:
  targets:
    - ./bxy-prod-ns-backbxy.yaml
    - ./bxy-prod-ns-bxy-fast-api.yaml
    - ./bxy-prod-ns-bxyfe-pc.yaml
    - ./bxy-prod-ns-bxy-main-api.yaml
    - ./bxy-prod-ns-bxyml-pc.yaml
    - ./bxy-prod-ns-bxymlrobot-pc.yaml
    - ./bxy-prod-ns-bxynotify-pc.yaml
    - ./bxy-prod-ns-bxy-quote-api.yaml
    - ./bxy-prod-ns-bxywebimports-pc.yaml
    - ./bxy-prod-ns-database-mongodb.yaml
    - ./bxy-prod-ns-databoxy-front-end.yaml
    - ./bxy-prod-ns-fecompraspc-frontend.yaml
    - ./bxy-prod-ns-fecompras-pc.yaml
    - ./bxy-prod-ns-mcp-server.yaml
    - ./bxy-prod-ns-mock-deployment.yaml
    - ./bxy-prod-ns-msgraphapis.yaml
    - ./bxy-prod-ns-nginx-facturasfe.yaml
    - ./bxy-prod-ns-nodesap-pc.yaml
    - ./endarea-ns-backendareaclient.yaml
    - ./endarea-ns-backendarea.yaml
    - ./endarea-ns-backendfileservice.yaml
    - ./endarea-ns-bxy-redis.yaml
    - ./endarea-ns-edrapidell.yaml
    - ./endarea-ns-edrbitacoraconsumer.yaml
    - ./endarea-ns-edremailrabbitconsumer.yaml
    - ./endarea-ns-edrnotifications.yaml
    - ./endarea-ns-edrportalservice.yaml
    - ./endarea-ns-emailtos3service.yaml
    - ./endarea-ns-endarea-frontend.yaml
    - ./endarea-ns-inventoryservice.yaml
    - ./endarea-ns-meconsumer.yaml
    - ./endarea-ns-techdirectservice.yaml
    - ./endarea-ns-ticketmanager-mcp-server.yaml
    - ./identity-ns-identity-lyn.yaml
    - ./identity-ns-keycloak.yaml
