apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bxy-quote-api
  title: bxy-quote-api
  description: Componente bxy-quote-api en namespace bxy-prod-ns
  annotations:
    backstage.io/kubernetes-id: bxy-quote-api
    backstage.io/kubernetes-namespace: bxy-prod-ns
  tags:
    - kubernetes
    - okd
    - bxy-prod-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
