apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fecompraspc-frontend
  title: fecompraspc-frontend
  description: Componente fecompraspc-frontend en namespace bxy-prod-ns
  annotations:
    backstage.io/kubernetes-id: fecompraspc-frontend
    backstage.io/kubernetes-namespace: bxy-prod-ns
  tags:
    - kubernetes
    - okd
    - bxy-prod-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
