apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mock-deployment
  title: mock-deployment
  description: Componente mock-deployment en namespace bxy-prod-ns
  annotations:
    backstage.io/kubernetes-id: mock-deployment
    backstage.io/kubernetes-namespace: bxy-prod-ns
  tags:
    - kubernetes
    - okd
    - bxy-prod-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
