apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-facturasfe
  title: nginx-facturasfe
  description: Componente nginx-facturasfe en namespace bxy-prod-ns
  annotations:
    backstage.io/kubernetes-id: nginx-facturasfe
    backstage.io/kubernetes-namespace: bxy-prod-ns
  tags:
    - kubernetes
    - okd
    - bxy-prod-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
