apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bxynotify-pc
  title: bxynotify-pc
  description: Componente bxynotify-pc en namespace bxy-prod-ns
  annotations:
    backstage.io/kubernetes-id: bxynotify-pc
    backstage.io/kubernetes-namespace: bxy-prod-ns
  tags:
    - kubernetes
    - okd
    - bxy-prod-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
