apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: msgraphapis
  title: msgraphapis
  description: Componente msgraphapis en namespace bxy-prod-ns
  annotations:
    backstage.io/kubernetes-id: msgraphapis
    backstage.io/kubernetes-namespace: bxy-prod-ns
  tags:
    - kubernetes
    - okd
    - bxy-prod-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
