apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: endarea-frontend
  title: endarea-frontend
  description: Componente endarea-frontend en namespace endarea-ns
  annotations:
    backstage.io/kubernetes-id: endarea-frontend
    backstage.io/kubernetes-namespace: endarea-ns
  tags:
    - kubernetes
    - okd
    - endarea-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
