apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bxy-redis
  title: bxy-redis
  description: Componente bxy-redis en namespace endarea-ns
  annotations:
    backstage.io/kubernetes-id: bxy-redis
    backstage.io/kubernetes-namespace: endarea-ns
  tags:
    - kubernetes
    - okd
    - endarea-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
