apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emailtos3service
  title: emailtos3service
  description: Componente emailtos3service en namespace endarea-ns
  annotations:
    backstage.io/kubernetes-id: emailtos3service
    backstage.io/kubernetes-namespace: endarea-ns
  tags:
    - kubernetes
    - okd
    - endarea-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
