apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: meconsumer
  title: meconsumer
  description: Componente meconsumer en namespace endarea-ns
  annotations:
    backstage.io/kubernetes-id: meconsumer
    backstage.io/kubernetes-namespace: endarea-ns
  tags:
    - kubernetes
    - okd
    - endarea-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
