apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edrportalservice
  title: edrportalservice
  description: Componente edrportalservice en namespace endarea-ns
  annotations:
    backstage.io/kubernetes-id: edrportalservice
    backstage.io/kubernetes-namespace: endarea-ns
  tags:
    - kubernetes
    - okd
    - endarea-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
