apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backendarea
  title: backendarea
  description: Componente backendarea en namespace endarea-ns
  annotations:
    backstage.io/kubernetes-id: backendarea
    backstage.io/kubernetes-namespace: endarea-ns
  tags:
    - kubernetes
    - okd
    - endarea-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
