apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: keycloak
  title: keycloak
  description: Componente keycloak en namespace identity-ns
  annotations:
    backstage.io/kubernetes-id: keycloak
    backstage.io/kubernetes-namespace: identity-ns
  tags:
    - kubernetes
    - okd
    - identity-ns
spec:
  type: service
  lifecycle: production
  owner: lyncorp
