apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ciclo-desarrollo
  annotations:
    github.com/project-slug: lyncorp/pc-backstage
spec:
  type: other
  lifecycle: unknown
  owner: guests
